# Generated by Django 4.1.5 on 2023-02-06 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CountryDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('confirmed', models.PositiveIntegerField()),
                ('deaths', models.PositiveIntegerField()),
                ('recovered', models.PositiveIntegerField()),
                ('active', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid19.country')),
            ],
        ),
        migrations.AddConstraint(
            model_name='countrydailystats',
            constraint=models.UniqueConstraint(models.F('date'), models.F('country'), name='date_country_unique'),
        ),
    ]
